=== andrewacashner/kircher/arca/input/arkText.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT arkText (head,text)>

<!ELEMENT head (title,wordsAuthor)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT wordsAuthor (#PCDATA)>

<!ELEMENT text (section+)>

<!ELEMENT section (lg+)>
<!ATTLIST section
    tone NMTOKEN #REQUIRED
    toneB NMTOKEN #IMPLIED
    musicMeter NMTOKEN #REQUIRED
    style NMTOKEN #REQUIRED
    textMeter NMTOKEN #REQUIRED>

<!ELEMENT lg (l)+>

<!ELEMENT l (#PCDATA)>

=== andrewacashner/kircher/arca/test/input/Boethius-Nubibus_atris-modes.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Nubibus atris Simplex Sexti toni mutans in secundum tonum</title>
    <wordsAuthor>Boethius (Consolatio philosophiae I:7)</wordsAuthor>
  </head>
  <text>
    <section style="Simple" tone="Tone6" musicMeter="Duple" textMeter="Adonium">
      <lg>
        <l>`Nu-bi-bus `a-tris</l>
        <l>`con-di-ta `nul-lum</l>
        <l>`fun-de-re `pos-sunt</l>
        <l>`si-de-ra `lu-men.</l>
      </lg>
    </section>
    <section style="Simple" tone="Tone2" musicMeter="Duple" textMeter="Adonium">
      <lg>
        <l>`Nu-bi-bus `a-tris</l>
        <l>`con-di-ta `nul-lum</l>
        <l>`fun-de-re `pos-sunt</l>
        <l>`si-de-ra `lu-men.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/input/prepared/simple/Bernardus-Hora_novissima.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Hora novissima</title>
    <wordsAuthor>Bernardus Morlanensis (De contemptu mundi I:1–4)</wordsAuthor>
  </head>
  <text>
    <section style="Simple" tone="Tone2" musicMeter="Duple" textMeter="Dactylicum">
      <lg>
        <l>`Ho-ra no-`vis-si-ma,</l>
        <l>`tem-po-ra `pes-si-ma</l>
      </lg>
    </section>
    <section style="Simple" tone="Tone2" musicMeter="Duple" textMeter="Adonium">
      <lg>
        <l>`sunt— vi-gi-`le-mus.</l>
      </lg>
    </section>
    <section style="Simple" tone="Tone2" musicMeter="TripleMinor" textMeter="Dactylicum">
      <lg>
        <l>`Ec-ce mi-`na-ci-ter</l>
        <l>`im-mi-net `ar-bi-ter</l>
      </lg>
    </section>
    <section style="Simple" tone="Tone2" musicMeter="TripleMinor" textMeter="Adonium">
      <lg>
        <l>`il-le sup-`re-mus.</l>
      </lg>
    </section>
    <section style="Simple" tone="Tone2" musicMeter="Duple" textMeter="Dactylicum">
      <lg>
        <l>`Im-mi-net `im-mi-net</l>
        <l>ut `ma-la `ter-mi-net,</l>
      </lg>
    </section>
    <section style="Simple" tone="Tone2" musicMeter="Duple" textMeter="Adonium">
      <lg>
        <l>`ae-qua co-`ro-net.</l>
      </lg>
    </section>
    <section style="Simple" tone="Tone2" musicMeter="TripleMajor" textMeter="Dactylicum">
      <lg>
        <l>`Rec-ta re-`mu-ne-ret,</l>
        <l>`an-xi-a `li-be-ret,</l>
      </lg>
    </section>
    <section style="Simple" tone="Tone2" musicMeter="TripleMajor" textMeter="Adonium">
      <lg>
        <l>`ae-the-ra `do-net.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/input/text/Veni_creator_Spiritus.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Veni creator Spiritus</title>
    <wordsAuthor>Rabanus Maurus</wordsAuthor>
  </head>
  <text>
    <section textMeter="IambicumArchilochicum" 
        style="{style}" mode="{mode}" musicMeter="{musicMeter}">
      <lg>
        <l>`Ve-ni cre-`a-tor `Spi-ri-tus</l>
        <l>`men-tes tu-`o-rum vi-`si-ta,</l>
        <l>`imp-le su-`per-na `gra-ti-a,</l>
        <l>quae tu cre-`as-ti `pec-to-ra.</l>
      </lg>
      <lg>
        <l>Qui `di-ce-ris Pa-`rac-li-tus,</l>
        <l>al-`tis-si-mi `do-num `De-i,</l>
        <l>fons `vi-vus, `i-gnis, `ca-ri-tas</l>
        <l>et spi-ri-`ta-lis `unct-i-o.</l>
      </lg>
      <lg>
        <l>Tu sep-ti-`for-mis `mu-ne-re,</l>
        <l>`di-gi-tus pa-`ter-nae `dex-terae</l>
        <l>tu `ri-te pro-`mis-sum `Pat-ris</l>
        <l>ser-`mo-ne `di-tans `gut-tu-ra.</l>
      </lg>
      <lg>
        <l>Ac-`cen-de `lu-men `sen-si-bus,</l>
        <l>in-`fun-de~a-`mo-rem `cor-di-bus,</l>
        <l>in-`fir-ma `nos-tri `cor-po-ris,</l>
        <l>vir-`tu-te `fir-mans per-`pe-ti. </l>
      </lg>
      <lg>
        <l>`Hos-tem re-`pel-las `long-i-us</l>
        <l>pa-`cem-que `do-nes `pro-ti-nus;</l>
        <l>duc-`to-re sic te `prae-vi-o</l>
        <l>vi-`te-mus `om-ne `nox-i-um.</l>
      </lg>
      <lg>
        <l>Per te sci-`a-mus da `Pat-rem</l>
        <l>nos-`ca-mus `at-que `Fil-i-um,</l>
        <l>te ut-ri-`us-que `Spi-ri-tum</l>
        <l>cre-`da-mus `om-ni `tem-po-re.</l>
      </lg>
      <lg>
        <l>`De-o `Pat-ri sit `glor-i-a,</l>
        <l>et `Fi-li-o qui~a `mor-tu-is</l>
        <l>Sur-`re-xit, ac Pa-`rac-li-to,</l>
        <l>in sae-cu-`lo-rum `sae-cu-la.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/input/prepared/simple/Ave_maris_stella.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Ave maris stella</title>
    <wordsAuthor>Liber Hymnarius</wordsAuthor>
  </head>
  <text>
    <section textMeter="IambicumEuripidaeum" style="Simple" musicMeter="TripleMajor" mode="Mode3">
      <lg>
        <l>`A-ve, `ma-ris `stel-la,</l>
        <l>`De-i `ma-ter `al-ma,</l>
        <l>`at-que `sem-per `vi-rgo,</l>
        <l>`fe-lix `coe-li `por-ta.</l>
      </lg>
      <lg>
        <l>`Su-mens `il-lud A-ve</l>
        <l>Gab-ri-`el-is `o-re,</l>
        <l>`fun-da nos in `pa-ce,</l>
        <l>`mu-tans `E-vae `no-men.</l>
      </lg>
      <lg>
        <l>`Sol-ve `vinc-la `re-is,</l>
        <l>`pro-fer `lu-men `cae-cis,</l>
        <l>`ma-la `nos-tra `pel-le,</l>
        <l>`bo-na `cunc-ta `pos-ce.</l>
      </lg>
    </section>
    <section textMeter="IambicumEuripidaeum" style="Simple" musicMeter="Duple" mode="Mode3">
      <lg>
        <l>`Mons-tra `te~es-se `mat-rem,</l>
        <l>`su-mat per te `pre-cem</l>
        <l>qui pro `no-bis `na-tus</l>
        <l>`tu-lit es-se `tu-us.</l>
      </lg>
      <lg>
        <l>`Vir-go `sin-gu-la-ris,</l>
        <l>`in-ter `om-nes `mi-tis,</l>
        <l>nos `cul-pis so-`lu-tos</l>
        <l>`mi-tes fac et `cas-tos.</l>
      </lg>
      <lg>
        <l>`Vi-tam `praes-ta `pu-ram,</l>
        <l>`i-ter `pa-ra `tu-tum,</l>
        <l>ut vi-`den-tes `Je-sum</l>
        <l>`sem-per col-lae-`te-mur.</l>
      </lg>
    </section>
    <section textMeter="IambicumEuripidaeum" style="Simple" musicMeter="TripleMinor" mode="Mode9">
      <lg>
        <l>Sit laus `De-o `Pat-ri,</l>
        <l>`sum-mo `Chris-to `de-cus,</l>
        <l>Spi-`ri-tu-i `Sanc-to</l>
        <l>`tri-bus `ho-nor `u-nus.</l>
      </lg>
    </section>
    <section textMeter="Prose" style="Simple" musicMeter="TripleMajor" mode="Mode9">
      <lg><l>A-`men.</l></lg>
    </section>
    </text>
  </arkText>

=== andrewacashner/kircher/arca/input/text/Ps-150.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Psalmi 150.</title>
    <wordsAuthor>Liber Usualis</wordsAuthor>
  </head>
  <text>
    <section textMeter="Prose" 
        style="{style}" mode="{mode}" musicMeter="{musicMeter}">
      <lg>
        <l>Al-le-`lu-ia.</l>
        <l>Lau-`da-te `Do-mi-num in `sanc-tis `e-jus;</l>
        <l>lau-`da-te `e-um in fir-ma-`men-to vir-`tu-tis `e-ius.</l>
      </lg>
      <lg>
        <l>`Om-nis `spi-ri-tus `lau-det `Do-mi-num! Al-le-`lu-ia.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/test/input/Sit_salus_illi.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Ex hymno Iste confessor Domini sacratus {styleName} {toneName}</title>
    <wordsAuthor>Breviarium Romanum</wordsAuthor>
  </head>
  <text>
    <section textMeter="Sapphicum" style="{style}" tone="{tone}" musicMeter="Duple">
      <lg>
        <l>Sit `sa-lus `il-li, `de-cus, `at-que `vir-tus,</l>
        <l>Qui `su-pra `c√¶-li re-`si-dens ca-`cu-men,</l>
        <l>`To-ti-us `mun-di `ma-chi-nam gu-`ber-nat</l>
        <l>`Tri-nus et `u-nus.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/input/Be_Thou_My_Vision.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arktext SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Be Thou My Vision</title>
    <wordsAuthor>Old Irish hymn, trans. Mary E. Byrne</wordsAuthor>
  </head>
  <text>
    <section textMeter="Dactylicum" musicMeter="Duple" style="Simple" mode="Mode4">
      <lg>
        <l>Be thou my `vi-sion, O Lord of my heart;</l>
        <l>naught be all else to me, save that thou art.</l>
        <l>Thou my best thought, _  by day or by night,</l>
        <l>`wa-king or `sleep-ing, thy `pre-sence my light.</l>
      </lg>
    </section>
    <section textMeter="Dactylicum" musicMeter="TripleMajor" style="Simple" mode="Mode4">
      <lg>
        <l>Be thou my wisdom, be thou my true word;</l>
        <l>I `e-ver with thee, and thou with me, Lord.</l>
        <l>Born of thy love, _ thy child may I be, </l>
        <l>thou in me `dwel-ling and I one with thee.</l>
      </lg>
    </section>
    <section textMeter="Dactylicum" musicMeter="TripleMinor" style="Simple" mode="Mode4">
      <lg>
        <l>High King of `hea-ven, when `vic-t’ry is won</l>
        <l>may I reach `heav-en’s joys, O bright heav’n’s Sun!</l>
        <l>Heart of my heart, _ what-`e-ver be-`fall,</l>
        <l>still be my `vi-sion, O `Ru-ler of all.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/test/web-lilypond/input/Away_in_a_Manger.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arktext SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Away in a Manger</title>
    <wordsAuthor>Anonymous</wordsAuthor>
  </head>
  <text>
    <section textMeter="PhaleuciumHendecasyllabicum" 
      musicMeter="Duple" style="Simple" mode="Mode6">
      <lg>
        <l>A-`way in a `man-ger, no crib for a bed,</l>
        <l>the `lit-tle Lord `Je-sus laid down his sweet head.</l>
        <l>The stars in the bright sky looked down where he lay,</l>
        <l>the `lit-tle Lord `Je-sus a-`sleep on the hay.</l>
      </lg>
    </section>
    <section textMeter="PhaleuciumHendecasyllabicum" 
      musicMeter="TripleMajor" style="Simple" mode="Mode6">
      <lg>
        <l>The `cat-tle are `low-ing, the `ba-by a-`wakes,</l>
        <l>but `lit-tle Lord `Je-sus no `cry-ing he makes.</l>
        <l>I love thee, Lord `Je-sus! Look down from the sky,</l>
        <l>and stay by my side un-`til `morn-ing is nigh.</l>
      </lg>
    </section>
    <section textMeter="PhaleuciumHendecasyllabicum" 
      musicMeter="Duple" style="Simple" mode="Mode6">
      <lg>
        <l>Be near me, Lord `Je-sus, I ask thee to stay</l>
        <l>close by me for-`ev-er, and love me, I pray.</l>
        <l>Bless all the dear `child-ren in thy `ten-der care,</l>
        <l>and fit us for `heav-en to live with thee there.</l>
      </lg>
    </section>
  </text>
</arkText>
