=== andrewacashner/kircher/arca/input/arkText.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT arkText (head,text)>

<!ELEMENT head (title,wordsAuthor)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT wordsAuthor (#PCDATA)>

<!ELEMENT text (section+)>

<!ELEMENT section (lg+)>
<!ATTLIST section
    tone NMTOKEN #REQUIRED
    toneB NMTOKEN #IMPLIED
    musicMeter NMTOKEN #REQUIRED
    style NMTOKEN #REQUIRED
    textMeter NMTOKEN #REQUIRED>

<!ELEMENT lg (l)+>

<!ELEMENT l (#PCDATA)>

=== andrewacashner/kircher/arca/input/prepared/simple/Shakespeare-If_Music_Be.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>If Music Be the Food of Love, Play On</title>
    <wordsAuthor>William Shakespeare (Twelfth Night I:i)</wordsAuthor>
  </head>
  <text>
    <section style="Florid" tone="Tone4" musicMeter="Duple" textMeter="Decasyllabicum">
      <lg>
        <l>If `mu-sic be the food of love, play on,</l>
        <l>give me `ex-cess of it, that, `sur-feit-ing,</l>
        <l>the `ap-pe`tite may `sick-en, and so die.</l>
        <l>That strain a-`gain. It had a `dy-ing fall;</l>
        <l>O, it came o’er my ear like the sweet sound</l>
        <l>that breathes u-`pon a bank of `vi-o-lets,</l>
        <l>`steal-ing and `giv-ing `o-dor. E-`nough, no more.</l>
        <l>’Tis not so sweet now as it was be-`fore.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/test/input/Boethius-Nubibus_atris.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Nubibus atris {styleName} {toneName}</title>
    <wordsAuthor>Boethius (Consolatio philosophiae I:7)</wordsAuthor>
  </head>
  <text>
    <section style="{style}" tone="{tone}" musicMeter="Duple" textMeter="Adonium">
      <lg>
        <l>`Nu-bi-bus `a-tris</l>
        <!--        <l>`con-di-ta `nul-lum</l>
        <l>`fun-de-re `pos-sunt</l>
          <l>`si-de-ra `lu-men.</l>
        -->
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/input/prepared/simple/Catullus-Viuamus_mea_Lesbia.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Viuamus, mea Lesbia, atque amemus</title>
    <wordsAuthor>Catullus (Carmina 5)</wordsAuthor>
  </head>
  <text>
    <section style="Simple" tone="Tone7" musicMeter="TripleMajor" textMeter="Hendecasyllabicum">
      <lg>
        <l>Vi-`ua-mus, `me-a `Les-bia,‿`at-que a-`me-mus,</l>
        <l>ru-mor-`es-que `se-num se-ue-ri-`o-rum</l>
        <l>`om-nes un-`i-us `aes-ti-`me-mus `as-sis.</l>
      </lg>
      <lg>
        <l>`So-les oc-`ci-de-re‿et `re-di-re `pos-sunt:</l>
        <l>`no-bis cum `se-mel oc-`ci-dit `bre-uis lux,</l>
        <l>nox est per-`pe-tu-`a u-na dor-mien-da.</l>
      </lg>
    </section>
    <section style="Simple" tone="Tone7" musicMeter="Duple" textMeter="Hendecasyllabicum">
      <lg>
        <l>Da mi `ba-si-a `mil-le, dein-de `cen-tum,</l>
        <l>dein `mil-le‿al-`te-ra, dein se-`cun-da `cen-tum,</l>
        <l>dein-de‿`us-que‿al-`te-ra `mil-le, dein-de `cen-tum.</l>
      </lg>
      <lg>
        <l>dein, cum `mi-li-a `mul-ta fe-`ce-ri-mus,</l>
        <l>con-tur-ba-bi-mus `il-la, ne sci-`a-mus,</l>
        <l>aut ne quis `ma-lus in-ui-de-re `pos-sit,</l>
        <l>cum `tan-tum `sci-at `es-se ba-si-`o-rum.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/input/text/Ave_Regina_Angelorum.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Ave Regina Angelorum</title>
    <wordsAuthor>Kircher?</wordsAuthor>
  </head>
  <text>
    <section textMeter="IambicumEnneasyllabicum"
      musicMeter="{musicMeter}" style="{style}" tone="{tone}">
    <lg>
      <l>`A-ve Re-`gi-na An-ge-`lo-rum,</l>
      <l>`A-ve me-`de-la po-pu-`lo-rum,</l>
      <l>`Sal-ve fons `vi-ta, `sal-ve `por-ta,</l>
      <l>Ex qua lux `mun-di `no-bis `or-ta.</l>
    </lg>
  </section>
</text>
</arkText>

=== andrewacashner/kircher/arca/input/text/Horace-Maecenas_atavis_edite_regibus.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Maecenas atavis edite regibus</title>
    <wordsAuthor>Horace, Ode 1.1</wordsAuthor>
  </head>
  <text>
    <section textMeter="Dodecasyllabicum" 
      style="{style}" mode="{mode}" musicMeter="{musicMeter}">
      <lg>
        <l>Mae-`ce-nas a-`ta-vis e-`di-te `re-gi-bus,</l>
        <l>o et prae-`si-dium et `dul-ce `de-cus `me-um,</l>
      </lg>
      <lg>
        <l>sunt quos cur-`ri-culo `pul-ve-rem O-`lym-pi-cum</l>
        <l>col-le-`gis-se `iu-vat me-`ta-que `fer-vi-dis</l>
        <l>e-vi-`ta-ta `ro-tis pal-`ma-que `no-bi-lis</l>
        <l>ter-`ra-rum `do-mi-nos e-`ve-hit ad `de-os;</l>
      </lg>
      <lg>
        <l>hunc, si mo-`bil-i-um `tur-ba Qui-`ri-ti-um</l>
        <l>`cer-tat ter-`ge-mi-nis `tol-le-re~ho-`no-ri-bus;</l>
      </lg>
      <lg>
        <l>`il-lum, si `prop-ri-o con-`di-dit hor-`re-o</l>
        <l>`quid-quid de `Li-by-cis `ver-ri-tur a-`re-is.</l>
      </lg>
    <lg>
      <l>Gau-`den-tem `pat-ri-os `fin-de-re `sar-cu-lo</l>
      <l>`ag-ros At-`ta-li-cis con-di-ci-`o-ni-bus</l>
      <l>`num-quam de-`mo-ve-as, ut `tra-be `Cy-pri-a</l>
      <l>`Myr-to-um `pa-vi-dus `nau-ta `se-cet `ma-re.</l>
    </lg>
  </section>
</text>
</arkText>
