=== andrewacashner/kircher/arca/input/arkText.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT arkText (head,text)>

<!ELEMENT head (title,wordsAuthor)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT wordsAuthor (#PCDATA)>

<!ELEMENT text (section+)>

<!ELEMENT section (lg+)>
<!ATTLIST section
    tone NMTOKEN #REQUIRED
    toneB NMTOKEN #IMPLIED
    musicMeter NMTOKEN #REQUIRED
    style NMTOKEN #REQUIRED
    textMeter NMTOKEN #REQUIRED>

<!ELEMENT lg (l)+>

<!ELEMENT l (#PCDATA)>

=== andrewacashner/kircher/arca/test/input/Ave_maris_stella.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Ave maris stella {styleName} {toneName}</title>
    <wordsAuthor>Liber Hymnarius</wordsAuthor>
  </head>
  <text>
    <section textMeter="IambicumEuripidaeum" 
      musicMeter="Duple" style="{style}" tone="{tone}">
      <lg>
        <l>`A-ve, `ma-ris `stel-la,</l>
        <l>`De-i `ma-ter `al-ma,</l>
        <l>`at-que `sem-per `vi-rgo,</l>
        <l>`fe-lix `coe-li `por-ta.</l>
      </lg>
    </section>
    </text>
  </arkText>

=== andrewacashner/kircher/arca/input/text/Iste_confessor_Domini.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Iste confessor Domini sacratus</title>
    <wordsAuthor>Breviarium Romanum</wordsAuthor>
  </head>
  <text>
    <section textMeter="Sapphicum" 
      style="{style}" mode="{mode}" musicMeter="{musicMeter}">
      <lg>
        <l>`Is-te Con-`fes-sor `Do-mi-ni sa-`cra-tus,</l>
        <l>`Fes-ta plebs `cu-ius ce-`leb-rat per `or-bem,</l>
        <l>`Ho-di-e `læ-tus `mer-u-it se-`cre-ta</l>
        <l>`Scan-de-re `cæ-li.</l>
      </lg>
      <lg>
        <l>`Un-de nunc `nos-ter `cho-rus in ho-`no-rem</l>
        <l>Ip-`si-us, `hym-num `ca-nit hunc li-`ben-ter,</l>
        <l>Ut `pi-is `e-ius `me-ri-tis iu-`ve-mur</l>
        <l>`Om-ne per `æ-vum.</l>
      </lg>
      <lg>
        <l>Sit `sa-lus `il-li, `de-cus, `at-que `vir-tus,</l>
        <l>Qui `su-pra `cæ-li re-`si-dens ca-`cu-men,</l>
        <l>`To-ti-us `mun-di `ma-chi-nam gu-`ber-nat</l>
        <l>`Tri-nus et `u-nus.</l>
      </lg>
    </section>
    <section textMeter="Prose" 
      style="{style}" mode="{mode}" musicMeter="{musicMeter}">
      <lg>
        <l>`A-men.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/input/prepared/florid/Stephanus-O_ter_quaterque_felix_Cicada.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>O ter quaterque felix Cicada</title>
    <wordsAuthor>Henricus Stephanus</wordsAuthor>
  </head>
  <text>
    <section textMeter="Anacreonticum"
      musicMeter="Duple" mode="Mode1" style="Florid">
      <lg>
        <l>O ter `qua-ter-que `fe-lix Ci-`ca-da, quae su-`pre-mis</l>
        <l>In ar-`bo-rum vi-re-tis, `ro-ris `pa-rum‿ut bi-`bis-ti,</l>
        <l>Can-`ta-re `dul-ce `gau-des re-`gi-nam `a-gens‿po-`ten-tem.</l>
      </lg>
      <lg>
        <l>Quod-`cun-que con-spi-`cia-ris `tuum est, quod `ar-va `gig-nunt,</l>
        <l>Quod `syl-va `cun-que `pro-fert. Te‿amp-`lec-ti-tur co-`lo-nus,</l>
        <l>Quod `e-jus in la-bo-res in-ju-ri-o-sa non sis:</l>
      </lg>
    </section>
    <section textMeter="Anacreonticum"
      musicMeter="Duple" mode="Mode4" style="Florid">
      <lg>
        <l>`Co-lunt, Ci-`ca-da, `te‿om-nes, di-`vi-na quod `pu-te-ris</l>
        <l>Aes-`ta-tis im-mi-`nen-tis. Te di-`li-gunt Ca-`moe-nae.</l>
        <l>Te di-li-`git-que `Phoe-bus, vo-`cem-que dat ca-`no-ram.</l>
      </lg>
      <lg>
        <l>Te non se-`nec-ta `car-pit. Fes-`ti-va, `ter-rae‿a-`lum-na,</l>
        <l>`Can-tus a-`mi-ca,‿et `om-nis `ma-li‿et do-`lo-ris `ex-pers.</l>
        <l>`Ul-la nec `auc-ta `car-ne, nec `auc-ta `san-gui-`ne‿ul-lo</l>
        <l>`Ip-sis `a-bes `pa-rum‿a diis.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/input/prepared/simple/Sit_salus_illi.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Fragmentum ex hymno Iste confessor Domini sacratus</title>
    <wordsAuthor>Breviarium Romanum</wordsAuthor>
  </head>
  <text>
    <section textMeter="$textMeter" style="$style" tone="$tone" musicMeter="$meter">
      <lg>
        <l>Sit `sa-lus `il-li, `de-cus, `at-que `vir-tus,</l>
        <l>Qui `su-pra `c√¶-li re-`si-dens ca-`cu-men,</l>
        <l>`To-ti-us `mun-di `ma-chi-nam gu-`ber-nat</l>
        <l>`Tri-nus et `u-nus.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/test/input/Ha_de_los_coros.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Ha de los Coros del cielo?</title>
    <wordsAuthor>Ignotus (1650)</wordsAuthor>
  </head>
  <text>
    <section style="Simple" tone="Tone2" musicMeter="TripleMinor" textMeter="Romance">
      <lg>
        <l>Ha de los `Co-ros del `cie-lo?</l>
        <l>`cu-yo mis-te-`rio-so `can-to</l>
        <l>sa-`gra-da can-`ción en-`to-na</l>
        <l>por los `sig-los de los `As-tros.</l>
      </lg>
      <lg>
        <l>Quién in-ter-`rom-`pe lo‿a-`cor-de</l>
        <l>`des-te sa-`gra-do Pa-`la-cio?</l>
        <l>que la ce-`les-te‿ar-mon-`í-a</l>
        <l>pen-`dien-te‿es-`tá de su `la-bio.</l>
      </lg>
      <lg>
        <l>`U-na no-ve-`dad sus-`pen-da</l>
        <l>`vues-tros `Mú-si-cos sa-`gra-dos,</l>
        <l>pues sus-`pen-de‿a las es-`fe-ras</l>
        <l>lo vo-`lub-le de sus `ar-cos.</l>
      </lg>
      <lg>
        <l>`Ha-gan `pau-sa los za`-fi-ros</l>
        <l>`des-te cua-`der-no‿es-tre-`lla-do,</l>
        <l>`de-jen do-bla-da la `ho-ja</l>
        <l>los a-`zu-les car-ta-`pa-cios.</l>
      </lg>
      <lg>
        <l>La con-so-`nan-cia más `nue-va</l>
        <l>es-cu-`chad, que la‿han for-`ma-do,</l>
        <l>`homb-re,‿y Dios en un pe-`se-bre,</l>
        <l>`cie-lo,‿y `tie-rra‿en un es-`tab-lo;</l>
      </lg>
      <lg>
        <l>Des-`puéb-len-se las es-`fe-ras</l>
        <l>de ce-`les-tes ciu-da-`da-nos</l>
        <l>pues `ba-jan a ser sus `glo-rias</l>
        <l>a-leg-`rí-as de los `cam-pos.</l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/input/Boethius-Nubibus_atris-florid.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Nubibus atris</title>
    <wordsAuthor>Boethius (Consolatio philosophiae I:7)</wordsAuthor>
  </head>
  <text>
    <section style="Simple" mode="Mode12" musicMeter="TripleMajor" textMeter="Adonium">
      <lg>
        <l>`Nu-bi-bus `a-tris</l>
        <l>`con-di-ta `nul-lum</l>
        <l>`fun-de-re `pos-sunt</l>
        <l>`si-de-ra `lu-men.</l>
      </lg>
    </section>
    <section style="Florid" mode="Mode12" musicMeter="Duple" textMeter="Adonium">
      <lg>
        <l>`Si `ma-re `vo-luens</l>
        <l>`tur-bi-dus `Aus-ter</l>
        <l>`mis-ce-at `aes-tum,</l>
        <l>`vi-tre-a `du-dum</l>
      </lg>
      <lg>
        <l>par que se-`re-nis</l>
        <l>`un-da di-`e-bus</l>
        <l>mox re-so-`lu-to</l>
        <l>`sor-di-da `cae-no</l>
      </lg>
      <lg>
        <l>`vi-si-bus `ob-stat,</l>
        <l>`qui-que va-`ga-tur</l>
        <l>`mon-ti-bus `al-tis</l>
        <l>`de-flu-us `am-nis</l>
      </lg>
      <lg>
        <l>`sae-pe re-`sis-tit</l>
        <l>`ru-pe so-`lu-ti</l>
        <l>`o-bi-ce `sa-xi</l>
        <l>tu `quo-que `si vis</l>
      </lg>
      <lg>
        <l>`lu-mi-ne `cla-ro</l>
        <l>`cer-ne-re `ve-rum,</l>
        <l>`tra-mi-te `rec-to</l>
        <l>`car-pe-re `cal-lem:</l>
      </lg>
    </section>
    <section style="Simple" mode="Mode5" musicMeter="Duple" textMeter="Adonium">
      <lg>
        <l>`gau-di-a `pel-le,</l>
        <l>`pel-le ti-`mo-rem</l>
        <l>`spem-que fu-`ga-to</l>
        <l>nec `do-lor `ad-sit,</l>
        <l>`nu-bi-la `mens est</l>
        <l>`vinc-ta que `fre-nis</l>
        <l>haec `u-bi `reg-nant.</l>
      </lg>
      </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/input/prepared/simple/Abide_with_Me.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Abide with Me</title>
    <wordsAuthor>Henry Francis Lyte (1847)</wordsAuthor>
  </head>
  <text>
    <section textMeter="Decasyllabicum" musicMeter="Duple" style="Simple" mode="Mode5">
      <lg>
        <l>A-`bide with me: fast falls the `e-ven-`tide;</l>
        <l>the `dark-ness `deep-ens; Lord, with me a-`bide.</l>
        <l>When other `help-ers fail and `com-forts flee,</l>
        <l>Help of the `help-less, O a-`bide with me.</l>
      </lg>
      <lg>

        <l>Swift to its close ebbs out life's `lit-tle day;</l>
        <l>earth's joys grow dim, its `glor-ies pass away.</l>
        <l>Change and de-`cay in all a-`round I see.</l>
        <l>O thou who `chang-est not, a-`bide with me.</l>
      </lg>
      <lg>
        <l>I need thy `pres-ence `ev-ery `pass-ing hour.</l>
        <l>What but thy grace can foil the `temp-ter's power?</l>
        <l>Who like thy-`self my guide and strength can be?</l>
        <l>Through cloud and `sun-shine, O a-`bide with me.</l>
      </lg>
    </section>
    <section textMeter="Decasyllabicum" musicMeter="TripleMajor" style="Simple" mode="Mode11">
      <lg>
        <l>I fear no foe with thee at hand to bless,</l>
        <l>ills have no weight, and tears no `bit-ter-ness.</l>
        <l>Where is death's sting? Where, grave, thy `vic-tor-y?</l>
        <l>I `tri-umph still, if thou a-`bide with me.</l>
      </lg>
      <lg>
        <l>Hold thou thy cross be-`fore my `clos-ing eyes.</l>
        <l>Shine through the gloom and point me to the skies.</l>
        <l>Heaven's `morn-ing breaks and earth's vain `sha-dows flee;</l>
        <l>in life, in death, O Lord, a-`bide with me. </l>
      </lg>
    </section>
  </text>
</arkText>

=== andrewacashner/kircher/arca/input/prepared/florid/Sit_salus_illi.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arkText SYSTEM "arkText.dtd">
<arkText>
  <head>
    <title>Iste confessor Domini sacratus (Conclusio)</title>
    <wordsAuthor>Breviarium Romanum</wordsAuthor>
  </head>
  <!-- tones 1, 2, 3, 4, 9, 10 for first three lines -->
  <!-- last line, tones 5, 6, 7, 8, 11, 12 -->
  <text>
    <section textMeter="Sapphicum" style="Florid" tone="Tone1" musicMeter="Duple">
      <lg>
        <l>Sit `sa-lus `il-li, `de-cus, `at-que `vir-tus,</l>
        <l>Qui `su-pra `c√¶-li re-`si-dens ca-`cu-men,</l>
        <l>`To-ti-us `mun-di `ma-chi-nam gu-`ber-nat</l>
      </lg>
    </section>
    <section textMeter="Adonium" style="Florid" tone="Tone6" musicMeter="Duple">
      <lg>
        <l>`Tri-nus et `u-nus.</l>
      </lg>
    </section>
    <section textMeter="Prose" style="Simple" tone="Tone1" musicMeter="Duple">
      <lg>
        <l>A-`men.</l>
      </lg>
    </section>
  </text>
</arkText>
